app:
  name: "Viper"
  version: "1.0.0"
  description: "A sample application using Viper for configuration management."
database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "secure_password"
  name: "db_v1"
  debug: true